name: audioplayers_tizen_example
description: Demonstrates how to use the audioplayers plugin.

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.17.0
  audioplayers_tizen:
    path: ../
  path_provider: ^1.6.10
  path_provider_tizen:
    path: ../../path_provider/
  http: ^0.12.2
  provider: ^3.0.0+1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/audio.mp3
    - assets/audio2.mp3
    - assets/messenger.mp3

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
