name: package_info_plus_tizen
description: Tizen implementation of the package_info_plus plugin
version: 1.0.0
homepage: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/package_info_plus

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: PackageInfoPlusTizenPlugin
        fileName: package_info_plus_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  package_info_plus_platform_interface: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
