name: audioplayers_tizen
description: Tizen implementation of the audioplayers plugin.
homepage: https://github.com/flutter-tizen/plugins
version: 1.0.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: AudioplayersTizenPlugin
        fileName: audioplayers_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.2
  integration_test_tizen:
    path: ../integration_test
  audioplayers: ^0.17.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
